import type { Size } from '@/components/atom/variable/type';
export interface HbIconProps {
  icon: HbIconName;
  size: Size;
}
export enum HbIconName {
  'graphic/heybit' = 'graphic/heybit',
  'system/filled/add' = 'system/filled/add',
  'system/filled/clear' = 'system/filled/clear',
  'system/filled/danger' = 'system/filled/danger',
  'system/filled/info' = 'system/filled/info',
  'system/filled/logo-binance' = 'system/filled/logo-binance',
  'system/filled/logo-bnb' = 'system/filled/logo-bnb',
  'system/filled/logo-btc' = 'system/filled/logo-btc',
  'system/filled/logo-busd' = 'system/filled/logo-busd',
  'system/filled/logo-eth' = 'system/filled/logo-eth',
  'system/filled/logo-facebook' = 'system/filled/logo-facebook',
  'system/filled/logo-instagram' = 'system/filled/logo-instagram',
  'system/filled/logo-medium' = 'system/filled/logo-medium',
  'system/filled/logo-telegram' = 'system/filled/logo-telegram',
  'system/filled/logo-tether' = 'system/filled/logo-tether',
  'system/filled/logo-trx' = 'system/filled/logo-trx',
  'system/filled/logo-tstory' = 'system/filled/logo-tstory',
  'system/filled/logo-twitter' = 'system/filled/logo-twitter',
  'system/filled/logo-usdc' = 'system/filled/logo-usdc',
  'system/filled/naver' = 'system/filled/naver',
  'system/filled/refresh' = 'system/filled/refresh',
  'system/filled/ic-sysyem-checkbox-able' = 'system/filled/ic-sysyem-checkbox-able',
  'system/filled/ic-sysyem-danger' = 'system/filled/ic-sysyem-danger',
  'system/outline/add' = 'system/outline/add',
  'system/outline/arrow-back' = 'system/outline/arrow-back',
  'system/outline/arrow-down' = 'system/outline/arrow-down',
  'system/outline/arrow-dropdown' = 'system/outline/arrow-dropdown',
  'system/outline/arrow-forward' = 'system/outline/arrow-forward',
  'system/outline/clear' = 'system/outline/clear',
  'system/outline/close' = 'system/outline/close',
  'system/outline/danger' = 'system/outline/danger',
  'system/outline/info' = 'system/outline/info',
  'system/outline/logo-binance' = 'system/outline/logo-binance',
  'system/outline/logo-bnb' = 'system/outline/logo-bnb',
  'system/outline/logo-btc' = 'system/outline/logo-btc',
  'system/outline/logo-busd' = 'system/outline/logo-busd',
  'system/outline/logo-eth' = 'system/outline/logo-eth',
  'system/outline/logo-instagram' = 'system/outline/logo-instagram',
  'system/outline/logo-medium' = 'system/outline/logo-medium',
  'system/outline/logo-telegram' = 'system/outline/logo-telegram',
  'system/outline/logo-tether' = 'system/outline/logo-tether',
  'system/outline/logo-trx' = 'system/outline/logo-trx',
  'system/outline/logo-tstory' = 'system/outline/logo-tstory',
  'system/outline/logo-usdc' = 'system/outline/logo-usdc',
  'system/outline/menu-more' = 'system/outline/menu-more',
  'system/outline/menu-side' = 'system/outline/menu-side',
  'system/outline/naver' = 'system/outline/naver',
  'system/outline/qr' = 'system/outline/qr',
  'system/outline/refresh' = 'system/outline/refresh',
  'system/outline/ic-sysyem-checkbox-able' = 'system/outline/ic-sysyem-checkbox-able',
  'system/outline/ic-sysyem-danger' = 'system/outline/ic-sysyem-danger'
}
