// import Hb from "@uprise-fin/heybit-ui-styled-components";
// console.log(Hb);
// import HbInput, { NAME as HbInputName } from "./hb-input";
// import HbSelect, { NAME as HbSelectName } from "./hb-select";
// import HbDialog, { NAME as HbDialogName } from "./hb-dialog";
// customElements.define(HbInputName, HbInput);
// customElements.define(HbSelectName, HbSelect);
// customElements.define(HbDialogName, HbDialog);
// export { HbInput, HbInputName, HbSelect, HbSelectName, HbDialog, HbDialogName };
import "./components/hb-input";
import "./components/hb-select";
import "./components/hb-dialog";
